services:
  dotnet:
    build:
      context: ./api
      dockerfile: ./JassSpace.Api/Dockerfile
    ports:
      - "5001:8080"
    env_file:
      - .env
    volumes:
      - /home/jassi/deployments/JassSpace/.logs/dotnet:/app/logs/dotnet
      - /home/jassi/deployments/JassSpace/.cache:/app/cache

  worker:
    build:
      context: ./api
      dockerfile: ./JassSpace.Worker/Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - dotnet
    volumes:
      - /home/jassi/deployments/JassSpace/logs/worker:/app/logs

  nextjs:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Uncomment and add environment variables as needed
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://localhost:z
    #   - DATABASE_URL=your_database_url
