services:
  dotnet:
    build:
      context: ./api
      dockerfile: ./JassSpace.Api/Dockerfile
    ports:
      - "5001:8080"
    env_file:
      - .env
    environment:
      - ApplyMigrationsOnStartup=${APPLY_MIGRATIONS:-false}
    restart: unless-stopped

  nextjs:
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5001}
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://dotnet:8080
    restart: unless-stopped
